linters:
  enable-all: true
  disable:
    # anarchy in the comments section
    - godox
    - godot

    # not very convenient
    - exhaustruct

    # not sure about this
    - ireturn

    # not following this one
    - testpackage

    # don't like the extra blank lines
    - wsl
    - nlreturn

    # not relevant
    - depguard

    # deprecated linters
    - gomnd
    - execinquery
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
