name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        go: ['1.19', '1.22']
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: --timeout 2m0s

      - name: Test
        run: make test
